FROM python:3.11-slim
WORKDIR /app

RUN apt-get update && apt-get install -y \
  tesseract-ocr \
  ocrmypdf \
  ghostscript \
  poppler-utils \
  && rm -rf /var/lib/apt/lists/*


# Same as Lambda build only we add the worker dependency group
COPY pyproject.toml uv.lock ./

RUN python -m pip install --upgrade pip && pip install "uv==0.5.24"

# RUN pip install --no-cache-dir \
#     "boto3>=1.42.44" \
#     "langchain>=1.2.0" \
#     "fastembed>=0.7.4" \
#     "sqlalchemy>=2.0.45"

# RUN pip install --no-cache-dir \
#     "alembic>=1.17.2" \
#     "fastapi>=0.128.2" \
#     "langchain-groq>=1.1.2" \
#     "langchain-community>=0.4.1" \
#     "langchain-qdrant>=1.1.0"


# RUN pip install --no-cache-dir \
#     "celery[sqs]>=5.6.2" \
#     "kombu>=5.6.2" \
#     "ocrmypdf>=16.0" \
#     "pymupdf4llm>=0.2.7"



# RUN pip install --no-cache-dir \
#     "pillow>=11.0.0,<12.0.0" \
#     "ghostscript>=0.8.1" \
#     "pytesseract>=0.3.10" 



RUN uv export \
    --format requirements-txt \
    --frozen \
    --no-dev \
    --no-install-project \
    --all-extras \
    -o requirements.txt

RUN python -m pip install --no-cache-dir -r requirements.txt

COPY src/ai_agents /app/ai_agents

CMD ["celery", "-A", "ai_agents.jobs.celery", "worker", "--loglevel=INFO"]
