from __future__ import annotations

LLM_DECISION_MAX_ATTEMPTS = 3
MAX_PATCH_ATTEMPTS = 2
MAX_FILES_TO_INSPECT = 10
VALIDATION_OUTPUT_MAX_CHARS = 2_000
VALIDATION_PROFILE_NAME = "coding-agent-default"
